addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo" % "0.11.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"  % "2.4.6")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"       % "1.0.2")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.9.3")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"  % "1.1.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "5.7.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"  % "0.10.0")
