addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo" % "0.13.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"  % "2.5.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"       % "1.0.2")
addSbtPlugin("org.scoverage"    % "sbt-scoverage" % "2.0.10")
//addSbtPlugin("com.eed3si9n"      % "sbt-assembly"  % "1.1.1")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.11.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.9.0")
