name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Java8:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [ 4, 5, 6 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      #      - name: Publish Local
      #        run: sbt +publishLocal

      - name: Build
        run: sbt compile

      - name: Code Style
        run: sbt scalafmtCheckAll

      - name: Checking headers
        run: sbt headerCheckAll

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0        

      - name: Run Test
        run: sbt coverage test coverageReport # test in scala2.13.x java 8

      - name: Aggregate coverage report
        run: sbt coverageAggregate

      - name: Upload test coverage report
        run: bash <(curl -s https://codecov.io/bash)

  Java11:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [ 4, 5, 6 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: sbt compile

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        
      - name: Run Test
        run: sbt coverage test coverageReport # test in scala2.13.x java 11