name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Build
        run: sbt compile

      - name: Checking Code Style
        run: sbt scalafmtCheckAll

      - name: Checking Scalafix
        run: sbt scalafixAll

      - name: Checking headers
        run: sbt headerCheckAll

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [ 4, 5, 6 ]
        java-version: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Run Test
        run: sbt coverage test coverageReport # test in scala2.13.x java 8

      - name: Aggregate coverage report
        run: sbt coverageAggregate

      - name: Upload test coverage report
        run: bash <(curl -s https://codecov.io/bash)
  
  ci:
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"          